### ISSUE TITLE
Generate QR-code of secret shared URL

### ISSUE THREAD

**Issue by binlab** [Luzifer/ots#61] opened 2022-07-21 23:17 UTC
Did you think about the feature of the **QR-code** generation shared link to the secret? It can be very convenient to share secrets between the laptop and the mobile for example. For the security reasons, the option can be disconnected in UI or globally

**Comment by Luzifer** [comment] 2023-06-10 18:25
This feature will be included in the next release!

**Closed** 2023-06-10 18:25 UTC
Labels: enhancement

**Comment by Gadgetroch** [comment] 2024-07-11 11:44
Hi @Luzifer ,

I want to copy this qr code for sharing but i can't, the qr code disappear while copy.

Can you update this ?

**Comment by Luzifer** [comment] 2024-07-11 11:46
> I want to copy this qr code for sharing but i can't, the qr code disappear while copy.

Hm for me the context-menu stays open and I can select "Copy Image" or "Copy Link to Image"… …which device are you using?

**Comment by Gadgetroch** [comment] 2024-07-11 11:48
Chrome

![Peek 11-07-2024 13-47](https://github.com/Luzifer/ots/assets/46190566/14a8c57e-4e83-4154-b942-75369d54d2ca)

**Comment by Luzifer** [comment] 2024-07-11 12:38
But with that "Copy Image" you should have the image in your clipboard… …so functionality-wise it should be fine (even though the QRCode was never intended to be copied)…

**Comment by Gadgetroch** [comment] 2024-07-11 12:39
I can confirm that qr code is not copied.

Maybe it's better to made something fold / unfold ?

Thank's

**Comment by Gadgetroch** [comment] 2024-09-27 23:16
This issue is always up

**Comment by Luzifer** [comment] 2024-09-28 12:20
> This issue is always up

Please be patient. This project is maintained in my spare time aside of a full-time job and firefighter duties. I do have it on my list, I will look into it.
